In [1]:
from keras import Input, layers

input_tensor = Input(shape=(32,))
dense = layers.Dense(32, activation='relu')

output_tensor = dense(input_tensor)

In [2]:
from keras.models import Sequential, Model
from keras import layers
from keras import Input

seq_model = Sequential()
seq_model.add(layers.Dense(32, activation='relu', input_shape=(64,)))
seq_model.add(layers.Dense(32, activation='relu'))
seq_model.add(layers.Dense(10, activation='softmax'))

input_tensor = Input(shape=(64,))
x = layers.Dense(32, activation='relu')(input_tensor)
x = layers.Dense(32, activation='relu')(x)
output_tensor = layers.Dense(10, activation='softmax')(x)

model = Model(input_tensor, output_tensor)
model.summary()

Model: "model"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         [(None, 64)]              0         
_________________________________________________________________
dense_4 (Dense)              (None, 32)                2080      
_________________________________________________________________
dense_5 (Dense)              (None, 32)                1056      
_________________________________________________________________
dense_6 (Dense)              (None, 10)                330       
Total params: 3,466
Trainable params: 3,466
Non-trainable params: 0
_________________________________________________________________


In [3]:
model.compile(optimizer='rmsprop', loss='categorical_crossentropy')
import numpy as np
x_train = np.random.random((1000, 64))
y_train = np.random.random((1000, 10))

model.fit(x_train, y_train, epochs=10, batch_size=128)
score = model.evaluate(x_train, y_train)

Epoch 1/10
8/8 [==============================] - 1s 2ms/step - loss: 11.8071
Epoch 2/10
8/8 [==============================] - 0s 3ms/step - loss: 12.0665
Epoch 3/10
8/8 [==============================] - 0s 3ms/step - loss: 12.8201
Epoch 4/10
8/8 [==============================] - 0s 3ms/step - loss: 14.5011
Epoch 5/10
8/8 [==============================] - 0s 2ms/step - loss: 16.6595
Epoch 6/10
8/8 [==============================] - 0s 4ms/step - loss: 19.2454
Epoch 7/10
8/8 [==============================] - 0s 3ms/step - loss: 22.6456
Epoch 8/10
8/8 [==============================] - 0s 3ms/step - loss: 26.9183
Epoch 9/10
8/8 [==============================] - 0s 3ms/step - loss: 31.4102
Epoch 10/10
32/32 [==============================] - 0s 2ms/step - loss: 39.9670


In [4]:
from keras.models import Model
from keras import layers
from keras import Input

text_vocabulary_size = 10000
question_vocabulary_size = 10000
answer_vocabulary_size = 500

text_input = Input(shape=(None,), dtype='int32', name='text')
embedded_text = layers.Embedding(text_vocabulary_size, 64)(text_input)
encoded_text = layers.LSTM(32)(embedded_text)
question_input = Input(shape=(None,), dtype='int32', name='question')

embedded_question = layers.Embedding(question_vocabulary_size, 32)(question_input)
encoded_question = layers.LSTM(16)(embedded_question)

concatenated = layers.concatenate([encoded_text, encoded_question], axis=-1)

answer = layers.Dense(answer_vocabulary_size, activation='softmax')(concatenated)

model = Model([text_input, question_input], answer)
model.compile(optimizer='rmsprop', loss='categorical_crossentropy', metrics=['acc'])

In [5]:
import numpy as np
from keras.utils import to_categorical

num_samples = 1000
max_length = 100

text = np.random.randint(1, text_vocabulary_size, size=(num_samples, max_length))
question = np.random.randint(1, question_vocabulary_size, size=(num_samples, max_length))

answers = np.random.randint(0, answer_vocabulary_size, size=num_samples)
answers = to_categorical(answers)

model.fit([text, question], answers, epochs=10, batch_size=128)

Epoch 1/10
8/8 [==============================] - 9s 133ms/step - loss: 6.2142 - acc: 0.0032
Epoch 2/10
8/8 [==============================] - 1s 124ms/step - loss: 6.1976 - acc: 0.0650
Epoch 3/10
8/8 [==============================] - 1s 115ms/step - loss: 6.1413 - acc: 0.0051
Epoch 4/10
8/8 [==============================] - 1s 132ms/step - loss: 6.0411 - acc: 0.0092
Epoch 5/10
8/8 [==============================] - 1s 117ms/step - loss: 5.9660 - acc: 0.0156
Epoch 6/10
8/8 [==============================] - 1s 111ms/step - loss: 5.8794 - acc: 0.0169
Epoch 7/10
8/8 [==============================] - 1s 104ms/step - loss: 5.8291 - acc: 0.0168
Epoch 8/10
8/8 [==============================] - 1s 121ms/step - loss: 5.6862 - acc: 0.0224
Epoch 9/10
8/8 [==============================] - 1s 145ms/step - loss: 5.6341 - acc: 0.0186
Epoch 10/10
8/8 [==============================] - 1s 114ms/step - loss: 5.5582 - acc: 0.0246


In [12]:
print(text)
print(question)
print(answers)

[[ 375 7749 2735 ... 4483  294 4798]
 [9396 5069 6951 ... 6112 5855 4898]
 [9572  136 3589 ... 6841 8066 5258]
 ...
 [3072 3442 1576 ... 2562 6000 7690]
 [6822 8342 3829 ... 2488 4980 1315]
 [6461 2344 2800 ... 8843  533 7952]]
[[7282 4699   57 ... 1195 6023 8900]
 [7112 2639 9492 ... 7046 3793 6239]
 [4533 8846 4675 ... 4840 1345  957]
 ...
 [9580 2501  959 ... 1832 4574 6605]
 [5866 1949 9341 ... 8026 2374 3874]
 [6278 9373 1658 ... 7046 9093 8955]]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [6]:
from keras import layers
from keras import Input 
from keras.models import Model 

vocabulary_size = 50000 
num_income_groups = 10 

posts_input = Input(shape=(None,), dtype='int32', name='posts')
embedded_posts = layers.Embedding(vocabulary_size,256)(posts_input)

x = layers.Conv1D(128, 5, activation='relu', padding='same')(embedded_posts)
x = layers.MaxPooling1D(5)(x)
x = layers.Conv1D(256, 5, activation='relu', padding='same')(x)
x = layers.Conv1D(256, 5, activation='relu', padding='same')(x)
x = layers.MaxPooling1D(5)(x)
x = layers.Conv1D(256, 5, activation='relu', padding='same')(x)
x = layers.Conv1D(256, 5, activation='relu', padding='same')(x) 
x = layers.GlobalMaxPooling1D()(x)
x = layers.Dense(128, activation='relu')(x) 

age_prediction = layers.Dense(1, name='age')(x)
income_prediction = layers.Dense(num_income_groups, activation='softmax',name='income')(x)
gender_prediction = layers.Dense(1, activation='sigmoid', name='gender')(x)
model = Model(posts_input,[age_prediction, income_prediction, gender_prediction])

model.summary()

Model: "model_2"
__________________________________________________________________________________________________
Layer (type)                    Output Shape         Param #     Connected to                     
posts (InputLayer)              [(None, None)]       0                                            
__________________________________________________________________________________________________
embedding_2 (Embedding)         (None, None, 256)    12800000    posts[0][0]                      
__________________________________________________________________________________________________
conv1d (Conv1D)                 (None, None, 128)    163968      embedding_2[0][0]                
__________________________________________________________________________________________________
max_pooling1d (MaxPooling1D)    (None, None, 128)    0           conv1d[0][0]                     
____________________________________________________________________________________________

In [7]:
model.compile(optimizer='rmsprop', loss=['mse', 'categorical_crossentropy', 'binary_crossentropy'])

In [8]:
import keras
num_samples = 1000 
max_length = 100 

posts = np.random.randint(1, vocabulary_size, size=(num_samples, max_length))
age_targets = np.random.randint(0, 100, size=(num_samples,1))
income_targets = np.random.randint(1, num_income_groups, size=(num_samples,1))
income_targets = keras.utils.to_categorical(income_targets,num_income_groups)
gender_targets = np.random.randint(0, 2, size=(num_samples,1))

model.fit(posts, [age_targets, income_targets, gender_targets], epochs=10, batch_size=64)


Epoch 1/10
16/16 [==============================] - 12s 506ms/step - loss: 2412.8521 - age_loss: 2405.2502 - income_loss: 6.5868 - gender_loss: 1.0149
Epoch 2/10
16/16 [==============================] - 8s 501ms/step - loss: 628.5668 - age_loss: 623.1308 - income_loss: 4.7272 - gender_loss: 0.7088
Epoch 3/10
16/16 [==============================] - 8s 518ms/step - loss: 570.8103 - age_loss: 567.6190 - income_loss: 2.5024 - gender_loss: 0.6890
Epoch 4/10
16/16 [==============================] - 8s 483ms/step - loss: 343.6989 - age_loss: 340.6554 - income_loss: 2.3262 - gender_loss: 0.7173
Epoch 5/10
16/16 [==============================] - 8s 481ms/step - loss: 445.5416 - age_loss: 442.5123 - income_loss: 2.3228 - gender_loss: 0.7066
Epoch 6/10
16/16 [==============================] - 8s 485ms/step - loss: 255.2176 - age_loss: 252.2418 - income_loss: 2.2807 - gender_loss: 0.6951
Epoch 7/10
16/16 [==============================] - 8s 499ms/step - loss: 358.6709 - age_loss: 355.7088 - inc

In [9]:
from keras import layers
from keras import Input
from keras.models import Model

num_samples = 100
num_symbols = 2

lstm = layers.LSTM(32)
left_input = Input(shape=(None, 128))
left_output = lstm(left_input)

right_input = Input(shape=(None, 128))
right_output = lstm(right_input)

merged = layers.concatenate([left_output, right_output], axis=-1)
predictions = layers.Dense(1, activation='sigmoid')(merged)

model = Model([left_input, right_input], predictions)
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['acc'])

left_data = np.random.randint(0, num_symbols, size=(num_samples,1,128))
right_data = np.random.randint(0, num_symbols, size=(num_samples,1,128))
matching_list = [np.random.randint(0, num_symbols) for _ in range(num_samples)]
targets = np.array(matching_list)

model.fit([left_data, right_data], targets)

4/4 [==============================] - 7s 4ms/step - loss: 0.6980 - acc: 0.5149


In [ ]:
#케라스 콜백 예시

In [10]:
import keras
callbacks_list = [
    keras.callbacks.EarlyStopping(
        monitor='val_acc',
        patience=1,
    ),
    keras.callbacks.ModelCheckpoint(
        filepath='my_model.h5',
        monitor='val_loss',
        save_best_onpy=True,
    )
]

model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])
model.fit(x, y, epochs=10, batch_size=32, callbacks=callbacks_list, validation_data=(x_val, y_val))

NameError: name 'y' is not defined

In [ ]:
callbacks_list = [
  keras.callbacks.ReduceLROnPlateau(
    monitor='val_loss'
    factor=0.1,
    patience=10,
  )
]

model.fit(x, y,epochs=10, batch_size=32, callbacks=callbacks_list,validation_data=(x_val, y_val))


In [ ]:
import keras
import numpy as np

class ActivationLogger(keras.callbacks.Callback):
    def set_model(self, model):
        self.model = model
        layer_outputs = [layer.output for layer in model.layers]
        self.activations_model = keras.models.Model(model.input,
        layer_outputs)
    
    def on_epoch_end(self, epoch, logs=None):
        if self.validation_data is None:
              raise RuntimeError('Requires validation_data.')
      
        validation_sample = self.validation_data[0][0:1]
        activations = self.activations_model.predict(validation_sample)
        f = open('activations_at_epoch_' + str(epoch) + '.npz', 'w')
        np.savez(f, activations)
        f.close()